### ISSUE TITLE
Not counting negative votes sometimes

### ISSUE THREAD

**Issue by philipjohn** [openpolitics/votebot#15] opened 2015-01-02 23:34 UTC
It *seems* like Votebot might be missing some votes. 

This has occurred on https://github.com/openpolitics/manifesto/pull/238#issuecomment-60883610 where @tmtmtmtm voted on a proposal 3 days after having his own proposal merged.

**Comment by Floppy** [comment] 2015-01-03 15:15
The problem is that the votebot doesn't think that @tmtmtmtm is a contributor, when clearly he is: https://github.com/openpolitics/manifesto/commits?author=tmtmtmtm

**Comment by Floppy** [comment] 2015-01-03 18:05
Right, the new updating thing updates contributors correctly, so this is now fixed.

**Closed by Floppy** 2015-01-03 18:05 UTC
